//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casa_de_colonies
{
    using System;
    using System.Collections.Generic;
    
    public partial class comarca
    {
        public int codigo_comarca { get; set; }
        public string nombre { get; set; }
    }
}
