//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casa_de_colonies
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class casacoloniesEntities : DbContext
    {
        public casacoloniesEntities()
            : base("name=casacoloniesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividad_casa> actividad_casa { get; set; }
        public virtual DbSet<activitat> activitat { get; set; }
        public virtual DbSet<administra_casa> administra_casa { get; set; }
        public virtual DbSet<administrador> administrador { get; set; }
        public virtual DbSet<casa> casa { get; set; }
        public virtual DbSet<comarca> comarca { get; set; }
        public virtual DbSet<inscripciones_casa_tanda> inscripciones_casa_tanda { get; set; }
        public virtual DbSet<monitor> monitor { get; set; }
        public virtual DbSet<monitor_tanda_casa> monitor_tanda_casa { get; set; }
        public virtual DbSet<monitor_tareas_tanda> monitor_tareas_tanda { get; set; }
        public virtual DbSet<niño> niño { get; set; }
        public virtual DbSet<niño_emparentado> niño_emparentado { get; set; }
        public virtual DbSet<personal> personal { get; set; }
        public virtual DbSet<poblacio> poblacio { get; set; }
        public virtual DbSet<tanda> tanda { get; set; }
        public virtual DbSet<tareas> tareas { get; set; }
    }
}
