//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casa_de_colonies
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitor_tareas_tanda
    {
        public string dni_monitor { get; set; }
        public int codigo_tarea { get; set; }
        public System.DateTime fecha_inicio_tanda { get; set; }
        public System.DateTime dia_tarea { get; set; }
    }
}
