//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casa_de_colonies
{
    using System;
    using System.Collections.Generic;
    
    public partial class niño_emparentado
    {
        public int carnet_niño { get; set; }
        public int carnet_hermano { get; set; }
    }
}
