//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenAccesDades
{
    using System;
    using System.Collections.Generic;
    
    public partial class receptes
    {
        public string nomRecepta { get; set; }
        public int idCategoria { get; set; }
        public int tempsPreparacioMinuts { get; set; }
        public string ingredients { get; set; }
        public string descripcioPreparacio { get; set; }
        public int dificultat { get; set; }
    }
}
