
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Button button10;

	private global::Gtk.Button button11;

	private global::Gtk.Button button12;

	private global::Gtk.Button button13;

	private global::Gtk.Button button15;

	private global::Gtk.Button button16;

	private global::Gtk.Button button17;

	private global::Gtk.Button button18;

	private global::Gtk.Button button19;

	private global::Gtk.Button button20;

	private global::Gtk.Button button21;

	private global::Gtk.Button button22;

	private global::Gtk.Button button23;

	private global::Gtk.Button button24;

	private global::Gtk.Button button25;

	private global::Gtk.Button button26;

	private global::Gtk.Button button27;

	private global::Gtk.Button button28;

	private global::Gtk.Button button29;

	private global::Gtk.Entry entry1;

	private global::Gtk.Entry entry2;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Button button14;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("A");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w1.X = 18;
		w1.Y = 67;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("B");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w2.X = 46;
		w2.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("C");
		this.fixed1.Add(this.button3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
		w3.X = 74;
		w3.Y = 66;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("D");
		this.fixed1.Add(this.button4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button4]));
		w4.X = 105;
		w4.Y = 67;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("E");
		this.fixed1.Add(this.button5);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
		w5.X = 136;
		w5.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("F");
		this.fixed1.Add(this.button6);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button6]));
		w6.X = 162;
		w6.Y = 66;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("G");
		this.fixed1.Add(this.button7);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button7]));
		w7.X = 193;
		w7.Y = 65;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("H");
		this.fixed1.Add(this.button8);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button8]));
		w8.X = 226;
		w8.Y = 64;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("I");
		this.fixed1.Add(this.button9);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button9]));
		w9.X = 259;
		w9.Y = 62;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button10 = new global::Gtk.Button();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString("J");
		this.fixed1.Add(this.button10);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button10]));
		w10.X = 283;
		w10.Y = 61;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("K");
		this.fixed1.Add(this.button11);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button11]));
		w11.X = 312;
		w11.Y = 63;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button12 = new global::Gtk.Button();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString("L");
		this.fixed1.Add(this.button12);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button12]));
		w12.X = 337;
		w12.Y = 64;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("M");
		this.fixed1.Add(this.button13);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button13]));
		w13.X = 368;
		w13.Y = 66;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("N");
		this.fixed1.Add(this.button15);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button15]));
		w14.X = 16;
		w14.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button16 = new global::Gtk.Button();
		this.button16.CanFocus = true;
		this.button16.Name = "button16";
		this.button16.UseUnderline = true;
		this.button16.Label = global::Mono.Unix.Catalog.GetString("Ñ");
		this.fixed1.Add(this.button16);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button16]));
		w15.X = 49;
		w15.Y = 121;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button17 = new global::Gtk.Button();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString("O");
		this.fixed1.Add(this.button17);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button17]));
		w16.X = 85;
		w16.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button18 = new global::Gtk.Button();
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString("P");
		this.fixed1.Add(this.button18);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button18]));
		w17.X = 119;
		w17.Y = 127;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button19 = new global::Gtk.Button();
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = global::Mono.Unix.Catalog.GetString("Q");
		this.fixed1.Add(this.button19);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button19]));
		w18.X = 144;
		w18.Y = 128;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button20 = new global::Gtk.Button();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString("R");
		this.fixed1.Add(this.button20);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button20]));
		w19.X = 180;
		w19.Y = 131;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button21 = new global::Gtk.Button();
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = global::Mono.Unix.Catalog.GetString("S");
		this.fixed1.Add(this.button21);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button21]));
		w20.X = 208;
		w20.Y = 131;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button22 = new global::Gtk.Button();
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseUnderline = true;
		this.button22.Label = global::Mono.Unix.Catalog.GetString("T");
		this.fixed1.Add(this.button22);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button22]));
		w21.X = 236;
		w21.Y = 132;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button23 = new global::Gtk.Button();
		this.button23.CanFocus = true;
		this.button23.Name = "button23";
		this.button23.UseUnderline = true;
		this.button23.Label = global::Mono.Unix.Catalog.GetString("U");
		this.fixed1.Add(this.button23);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button23]));
		w22.X = 269;
		w22.Y = 133;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button24 = new global::Gtk.Button();
		this.button24.CanFocus = true;
		this.button24.Name = "button24";
		this.button24.UseUnderline = true;
		this.button24.Label = global::Mono.Unix.Catalog.GetString("V");
		this.fixed1.Add(this.button24);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button24]));
		w23.X = 301;
		w23.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button25 = new global::Gtk.Button();
		this.button25.CanFocus = true;
		this.button25.Name = "button25";
		this.button25.UseUnderline = true;
		this.button25.Label = global::Mono.Unix.Catalog.GetString("W");
		this.fixed1.Add(this.button25);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button25]));
		w24.X = 333;
		w24.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button26 = new global::Gtk.Button();
		this.button26.CanFocus = true;
		this.button26.Name = "button26";
		this.button26.UseUnderline = true;
		this.button26.Label = global::Mono.Unix.Catalog.GetString("X");
		this.fixed1.Add(this.button26);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button26]));
		w25.X = 370;
		w25.Y = 139;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button27 = new global::Gtk.Button();
		this.button27.CanFocus = true;
		this.button27.Name = "button27";
		this.button27.UseUnderline = true;
		this.button27.Label = global::Mono.Unix.Catalog.GetString("Y");
		this.fixed1.Add(this.button27);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button27]));
		w26.X = 18;
		w26.Y = 174;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button28 = new global::Gtk.Button();
		this.button28.CanFocus = true;
		this.button28.Name = "button28";
		this.button28.UseUnderline = true;
		this.button28.Label = global::Mono.Unix.Catalog.GetString("Z");
		this.fixed1.Add(this.button28);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button28]));
		w27.X = 48;
		w27.Y = 174;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button29 = new global::Gtk.Button();
		this.button29.CanFocus = true;
		this.button29.Name = "button29";
		this.button29.UseUnderline = true;
		this.button29.Label = global::Mono.Unix.Catalog.GetString("Ok");
		this.fixed1.Add(this.button29);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button29]));
		w28.X = 496;
		w28.Y = 97;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
		w29.X = 16;
		w29.Y = 34;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add(this.entry2);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
		w30.X = 193;
		w30.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Mensaje");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w31.X = 75;
		w31.Y = 4;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Mensaje Cifrado");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w32.X = 233;
		w32.Y = 7;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button14 = new global::Gtk.Button();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString(" ");
		this.fixed1.Add(this.button14);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button14]));
		w33.X = 183;
		w33.Y = 198;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 573;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button2.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button3.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button4.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button5.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button6.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button7.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button8.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button9.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button10.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button11.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button12.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button15.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button16.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button17.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button18.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button19.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button20.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button21.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button22.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button23.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button24.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button25.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button26.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button27.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button28.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
		this.button29.Clicked += new global::System.EventHandler(this.botonOk_Click);
		this.button14.Clicked += new global::System.EventHandler(this.botonesLetras_Click);
	}
}
